paths:
  data_path: "./data/output_final_sorted.txt"
  model_save_path: "./language_model/models/"
  model_load_path: "./language_model/model/"
  log_path: "./language_model/logs/"
  model_zip_url: "https://github.com/brooks-christensen/alan_watts_bot/releases/download/1.0.0/03-07-2025T14-10-08.zip"
  model_dir: "./language_model/model"

general:
  seed_val: 42

tokenizer:
  max_length: 768

optimizer:
  type: "AdamW"
  adamw:
    lr: 1e-5
    adam_epsilon: 1e-8
    weight_decay: 0.02
    beta1: 0.9
    beta2: 0.99

training:
  logger_level: "INFO"
  batch_size: 2
  train_percent: 0.8
  epochs: 100
  warmup_steps: 1e2
  sample_every: 100
  max_patience: 10
  num_workers: 4
  
testing:
  logger_level: "DEBUG"
  test_flag: False
  test_length: 10000

generation:
  do_sample: True
  temperature: 1.0
  top_k: 50
  max_length: 300
  top_p: 0.95
  num_return_sequences: 3
  num_return_sequences_training: 1
  model_version: "03-07-2025T14-10-08"